apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260515-135114-i1fx6c0p560w-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260515-135114-i1fx6c0p560w.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260515-135114-i1fx6c0p560w-service
            port:
              number: 80
