apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260515-135114-i1fx6c0p560w-service
spec:
  selector:
    app: enterprise-system-20260515-135114-i1fx6c0p560w
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
